name: Memory

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        run: ./gradlew lintDebug

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: ./gradlew testDebugUnitTest

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: assemble
        run: ./gradlew assembleDebug
