name: Memory

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  cancel-previous:
    name: Cancel Previous
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Build
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: lint
        run: make clean lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: test
        run: make clean test

  build:
    name: Build APK
    runs-on: ubuntu-latest
    needs: cancel-previous
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - name: assemble
        run: make clean assemble
